"""updated

Revision ID: 568eaf6c0e0b
Revises: c8348c739dff
Create Date: 2024-01-20 22:04:20.719385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568eaf6c0e0b'
down_revision = 'c8348c739dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('admins', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###
