"""updated

Revision ID: c8348c739dff
Revises: 8eb260a6e7b3
Create Date: 2024-01-20 21:57:41.021263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8348c739dff'
down_revision = '8eb260a6e7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'password')
    # ### end Alembic commands ###
